<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Channel;
use Illuminate\Database\Seeder;

class ChannelSeeder extends Seeder
{
    public function run(): void
    {
        $channels = [
            [
                'sort_order'  => 1,
                'color'       => 'primary',
                'name'        => ['es' => 'Retail & Autoservicio', 'en' => 'Retail & Grocery'],
                'slug'        => ['es' => 'retail-autoservicio',   'en' => 'retail-grocery'],
                'tagline'     => ['es' => 'El proveedor TIF 422 que pasa cualquier auditoría de homologación.', 'en' => 'The TIF 422 supplier that passes any homologation audit.'],
                'description' => ['es' => 'Abastecimiento continuo a cadenas de autoservicio con documentación TIF 422 completa, trazabilidad verificable por lote y empaque certificado para auditoría de homologación de proveedores.', 'en' => 'Continuous supply for supermarket chains with full TIF 422 documentation, lot-traceable packaging and certifications required for supplier homologation audits.'],
                'long_description' => ['es' => 'Las cadenas de autoservicio más exigentes de México tienen un requisito indiscutible: constancia TIF activa, trazabilidad lote a lote y empaque que supere la auditoría de homologación. Soma Meat Co cumple los tres desde el primer embarque. Operamos bajo supervisión veterinaria SENASICA-SADER permanente, con HACCP documentado por turno y código de lote trazable desde origen hasta anaquel. Entregamos en presentaciones estándar para autoservicio: charola termoformada, empaque al vacío o bolsa skin, con EAN-13 impreso y fecha de caducidad verificable.', 'en' => 'The most demanding retail chains in Mexico have one non-negotiable requirement: active TIF certificate, lot-to-lot traceability, and packaging that passes the homologation audit. Soma Meat Co delivers all three from the first shipment. We operate under permanent SENASICA-SADER veterinary supervision, with shift-documented HACCP and lot codes traceable from origin to shelf.'],
                'features'     => ['es' => ['Constancia TIF 422 activa y vigente', 'Trazabilidad lote a lote documentada', 'Empaque certificado para anaquel', 'Homologación de proveedor expedita', 'Supervisión veterinaria SENASICA permanente', 'HACCP documentado por turno'], 'en' => ['Active TIF 422 supplier certificate', 'Lot-to-lot documented traceability', 'Certified retail-ready packaging', 'Expedited supplier homologation', 'Permanent SENASICA veterinary supervision', 'Shift-documented HACCP']],
                'proof_points' => [['value' => 'TIF 422', 'label_es' => 'Certificación federal', 'label_en' => 'Federal certification'], ['value' => '100%', 'label_es' => 'Trazabilidad por lote', 'label_en' => 'Lot traceability'], ['value' => '48 h', 'label_es' => 'Respuesta a cotización', 'label_en' => 'Quote turnaround'], ['value' => '10+', 'label_es' => 'Cadenas atendidas', 'label_en' => 'Chains served']],
                'pain_points'  => [['title_es' => '¿Tu proveedor actual no tiene TIF?', 'title_en' => 'Supplier lacks TIF?', 'body_es' => 'Sin TIF no entras al anaquel de las cadenas líderes. Nosotros ya tenemos la constancia activa.', 'body_en' => 'Without TIF you cannot enter leading retail chains. We already hold the active certificate.'], ['title_es' => '¿Fallas en auditorías de homologación?', 'title_en' => 'Failing homologation audits?', 'body_es' => 'Nuestro expediente técnico cubre todos los puntos de verificación CCTIF y BPM.', 'body_en' => 'Our technical file covers all CCTIF and GMP verification points.'], ['title_es' => '¿Necesitas trazabilidad por lote?', 'title_en' => 'Need lot-level traceability?', 'body_es' => 'Cada embarque lleva código de lote, fecha de sacrificio, especie, veterinario y destino.', 'body_en' => 'Every shipment carries lot code, slaughter date, species, vet name and destination.']],
                'process_steps'=> [['n' => '01', 'title_es' => 'Cotización en 48 h', 'title_en' => 'Quote in 48 h', 'body_es' => 'Envías tu ficha técnica o especificación. Te respondemos con precio, presentación y capacidad.', 'body_en' => 'Send your spec. We reply with price, presentation and available capacity.'], ['n' => '02', 'title_es' => 'Validación de muestra', 'title_en' => 'Sample validation', 'body_es' => 'Enviamos muestra física con certificado TIF, análisis microbiológico y ficha de trazabilidad.', 'body_en' => 'We send a physical sample with TIF certificate, microbio analysis and traceability sheet.'], ['n' => '03', 'title_es' => 'Homologación', 'title_en' => 'Homologation', 'body_es' => 'Entregamos el expediente completo: constancia TIF, HACCP, BPM, análisis y permisos.', 'body_en' => 'We deliver the full file: TIF certificate, HACCP, GMP, analyses and sanitary permits.'], ['n' => '04', 'title_es' => 'Abastecimiento continuo', 'title_en' => 'Ongoing supply', 'body_es' => 'Producción programada por semana. Reportes de lote y trazabilidad en cada entrega.', 'body_en' => 'Weekly scheduled production. Lot reports and traceability on every delivery.']],
            ],
            [
                'sort_order'  => 2,
                'color'       => 'copper',
                'name'        => ['es' => 'HORECA', 'en' => 'HORECA'],
                'slug'        => ['es' => 'horeca', 'en' => 'horeca'],
                'tagline'     => ['es' => 'Cortes a ficha técnica para chefs que no negocian la calidad.', 'en' => "Cuts to exact spec for chefs who don't compromise on quality."],
                'description' => ['es' => 'Hoteles, restaurantes y catering. Cortes a ficha técnica, porciones calibradas y protocolo HACCP documentado por lote. 5 especies. KOSHER bajo solicitud.', 'en' => 'Hotels, restaurants and catering. Cuts to exact technical specs, calibrated portions and HACCP-documented protocol. 5 species available. Kosher on request.'],
                'long_description' => ['es' => 'Un chef de hotel o cadena de restaurantes necesita exactamente lo que especifica: el corte correcto, el peso correcto, la temperatura correcta. Soma Meat Co procesa a ficha técnica del cliente — no al estándar del rastro. Cada corte lleva número de lote, especie, fecha de sacrificio y rendimiento documentado. Si operas bajo certificación KOSHER, coordinamos directamente con el supervisor KC.', 'en' => "A hotel or restaurant chain chef needs exactly what they specify: the right cut, right weight, right temperature. Soma Meat Co processes to the client's technical spec — not the slaughterhouse standard. Every cut carries lot number, species, slaughter date and documented yield."],
                'features'     => ['es' => ['Cortes a ficha técnica del cliente', 'Porciones calibradas por peso exacto', 'HACCP documentado por lote', 'KOSHER KC disponible bajo solicitud', '5 especies: bovino, ovino, caprino, porcino, ave', 'Empaque al vacío para shelf-life extendido'], 'en' => ['Cuts to client technical spec', 'Portions calibrated by exact weight', 'HACCP documented per lot', 'KOSHER KC available on request', '5 species: beef, lamb, goat, pork, poultry', 'Vacuum pack for extended shelf life']],
                'proof_points' => [['value' => '5', 'label_es' => 'Especies disponibles', 'label_en' => 'Species available'], ['value' => 'HACCP', 'label_es' => 'Documentado por lote', 'label_en' => 'Documented per lot'], ['value' => 'KOSHER', 'label_es' => 'KC certificado', 'label_en' => 'KC certified'], ['value' => '< 4°C', 'label_es' => 'Cadena de frío', 'label_en' => 'Cold chain']],
                'pain_points'  => [['title_es' => '¿Tu proveedor no corta a tu ficha técnica?', 'title_en' => 'Supplier ignores your spec?', 'body_es' => 'Procesamos exactamente al gramaje y corte que defines. Sin variaciones no autorizadas.', 'body_en' => 'We process exactly to the weight and cut you define. No unauthorized variations.'], ['title_es' => '¿Necesitas KOSHER sin cambiar de proveedor?', 'title_en' => 'Need KOSHER without switching suppliers?', 'body_es' => 'Operamos con supervisión KC activa. Podemos separar líneas para cumplimiento KOSHER.', 'body_en' => 'We operate with active KC supervision. We can separate lines for KOSHER compliance.'], ['title_es' => '¿Merma variable te descuadra el food cost?', 'title_en' => 'Variable yield ruining food cost?', 'body_es' => 'Entregamos rendimiento documentado por corte. Predice tu costo antes de poner el platillo en carta.', 'body_en' => 'We deliver documented yield per cut. Predict your cost before putting the dish on menu.']],
                'process_steps'=> [['n' => '01', 'title_es' => 'Envías tu ficha técnica', 'title_en' => 'Send your spec sheet', 'body_es' => 'Corte, gramaje, presentación, especie, frecuencia de entrega.', 'body_en' => 'Cut, weight, presentation, species, delivery frequency.'], ['n' => '02', 'title_es' => 'Muestra y validación', 'title_en' => 'Sample and validation', 'body_es' => 'Procesamos muestra según tu ficha. Ajustamos hasta que la validación sea positiva.', 'body_en' => 'We process a sample to your spec. We adjust until you validate.'], ['n' => '03', 'title_es' => 'Producción programada', 'title_en' => 'Scheduled production', 'body_es' => 'Confirmamos calendario de entregas. Cada lote con etiqueta HACCP y fecha de caducidad.', 'body_en' => 'We confirm delivery schedule. Each lot with HACCP label and expiry date.'], ['n' => '04', 'title_es' => 'Entrega y soporte', 'title_en' => 'Delivery and support', 'body_es' => 'Ejecutivo de cuenta asignado. Ajustes de ficha en 24 h.', 'body_en' => 'Assigned account executive. Spec adjustments in 24 h.']],
            ],
            [
                'sort_order'  => 3,
                'color'       => 'evergreen',
                'name'        => ['es' => 'Distribución', 'en' => 'Distribution'],
                'slug'        => ['es' => 'distribucion', 'en' => 'distribution'],
                'tagline'     => ['es' => 'Volumen mayorista con trazabilidad TIF 422 en cada caja.', 'en' => 'Wholesale volume with TIF 422 traceability in every box.'],
                'description' => ['es' => 'Distribuidores y mayoristas con presentaciones etiquetadas por lote, constancia TIF 422 activa y documentación de trazabilidad completa.', 'en' => 'Regional and national distributors with lot-labeled presentations, active TIF 422 certificate and full traceability documentation.'],
                'long_description' => ['es' => 'Si distribuyes carne a nivel regional o nacional, tu negocio depende de que el proveedor entregue en tiempo, con documentación completa y sin reclamaciones sanitarias. Soma Meat Co opera con constancia TIF 422 activa, lo que significa que tus clientes institucionales pueden homologarte como proveedor confiable. Entregamos en presentaciones mayoristas con etiquetado por lote y ficha de trazabilidad incluida.', 'en' => 'If you distribute meat regionally or nationally, your business depends on the supplier delivering on time, with full documentation and no sanitary claims. Soma Meat Co operates with an active TIF 422 certificate, meaning your institutional clients can homologate you as a reliable supplier.'],
                'features'     => ['es' => ['Constancia TIF 422 activa transferible', 'Presentaciones mayorista y media canal', 'Etiquetado por lote en cada caja', 'Ficha de trazabilidad por embarque', 'Capacidad 18–21 ton/día', 'NDA disponible para distribuidores exclusivos'], 'en' => ['Transferable active TIF 422 certificate', 'Wholesale and half-carcass presentations', 'Lot labeling on every box', 'Traceability sheet per shipment', 'Capacity 18–21 ton/day', 'NDA available for exclusive distributors']],
                'proof_points' => [['value' => '18–21 t', 'label_es' => 'Capacidad diaria', 'label_en' => 'Daily capacity'], ['value' => 'TIF 422', 'label_es' => 'Transferible a cliente', 'label_en' => 'Transferable to client'], ['value' => '100%', 'label_es' => 'Trazabilidad por lote', 'label_en' => 'Lot traceability'], ['value' => 'NDA', 'label_es' => 'Disponible', 'label_en' => 'Available']],
                'pain_points'  => [['title_es' => '¿Tu proveedor no tiene TIF y pierdes clientes?', 'title_en' => 'Losing clients because supplier lacks TIF?', 'body_es' => 'Con nuestra constancia TIF activa accedes a clientes institucionales que lo exigen.', 'body_en' => 'With our active TIF certificate you can access institutional clients that require it.'], ['title_es' => '¿Problemas de volumen en temporada alta?', 'title_en' => 'Volume issues during peak season?', 'body_es' => 'Nuestra capacidad de 18–21 ton/día nos permite ser tu respaldo en temporadas de alta demanda.', 'body_en' => 'Our 18–21 ton/day capacity lets us be your backup during peak demand seasons.'], ['title_es' => '¿Reclamaciones sanitarias de tus clientes?', 'title_en' => 'Sanitary claims from your clients?', 'body_es' => 'Cada caja tiene lote, veterinario responsable y fecha. La cadena de responsabilidad es clara.', 'body_en' => 'Every box has lot number, responsible vet and date. The chain of responsibility is clear.']],
                'process_steps'=> [['n' => '01', 'title_es' => 'Solicitud de cotización', 'title_en' => 'Quote request', 'body_es' => 'Especifica especie, volumen, presentación y frecuencia. Respondemos en 48 h.', 'body_en' => 'Specify species, volume, presentation and frequency. We respond in 48 h.'], ['n' => '02', 'title_es' => 'Revisión de capacidad', 'title_en' => 'Capacity review', 'body_es' => 'Confirmamos disponibilidad de producción y calendario de entregas por semana.', 'body_en' => 'We confirm production availability and weekly delivery schedule.'], ['n' => '03', 'title_es' => 'Primer embarque con docs', 'title_en' => 'First shipment with docs', 'body_es' => 'Constancia TIF, análisis, ficha de trazabilidad y etiquetado por lote desde el día uno.', 'body_en' => 'TIF certificate, analysis, traceability sheet and lot labeling from day one.'], ['n' => '04', 'title_es' => 'Abastecimiento regular', 'title_en' => 'Regular supply', 'body_es' => 'Programa semanal confirmado. Ejecutivo asignado para ajustes de volumen o presentación.', 'body_en' => 'Confirmed weekly schedule. Assigned executive for volume or presentation adjustments.']],
            ],
            [
                'sort_order'  => 4,
                'color'       => 'primary',
                'name'        => ['es' => 'Marca Propia', 'en' => 'Private Label'],
                'slug'        => ['es' => 'marca-propia', 'en' => 'private-label'],
                'tagline'     => ['es' => 'Tu marca, nuestra planta TIF 422. Del concepto al anaquel.', 'en' => 'Your brand, our TIF 422 plant. From concept to shelf.'],
                'description' => ['es' => 'Tu fórmula, tu empaque, tu código EAN-13 — producidos en nuestra planta TIF 422. NDA disponible. Capacidad: 18–21 ton/día.', 'en' => 'Your formula, your packaging, your EAN-13 code — produced in our TIF 422 facility. NDA available. Capacity: 18–21 ton/day.'],
                'long_description' => ['es' => 'Lanzar una marca de carne propia sin planta propia era imposible hasta que llegamos. Soma Meat Co maquila bajo NDA con capacidad de 18–21 ton/día. Tu fórmula de corte, tu diseño de empaque, tu código EAN-13 y tu fecha de caducidad — todo producido bajo certificación TIF 422, HACCP y KOSHER KC. Desde cadenas de supermercados que quieren diferenciarse hasta empresas de foodtech que necesitan producción confiable, trabajamos con marcas que entienden que la calidad de su producto empieza en el rastro.', 'en' => "Launching your own meat brand without your own plant was impossible — until now. Soma Meat Co manufactures under NDA with 18–21 ton/day capacity. Your cut formula, your packaging design, your EAN-13 code and expiry date — all produced under TIF 422, HACCP and KOSHER KC certification."],
                'features'     => ['es' => ['NDA firmado desde el primer contacto', 'Tu fórmula de corte exclusiva', 'Empaque con tu marca y diseño', 'Código EAN-13 registrable', 'Producción bajo TIF 422 + HACCP + KOSHER', 'Capacidad 18–21 ton/día según especie'], 'en' => ['NDA signed from first contact', 'Your exclusive cut formula', 'Packaging with your brand and design', 'Registrable EAN-13 code', 'Production under TIF 422 + HACCP + KOSHER', 'Capacity 18–21 ton/day by species']],
                'proof_points' => [['value' => 'NDA', 'label_es' => 'Desde el primer contacto', 'label_en' => 'From first contact'], ['value' => '18–21 t', 'label_es' => 'Capacidad diaria', 'label_en' => 'Daily capacity'], ['value' => 'EAN-13', 'label_es' => 'Código registrable', 'label_en' => 'Registrable code'], ['value' => '3', 'label_es' => 'Certificaciones activas', 'label_en' => 'Active certifications']],
                'pain_points'  => [['title_es' => '¿Tienes la marca pero no la planta?', 'title_en' => 'Have the brand but not the plant?', 'body_es' => 'Nosotros somos tu planta. TIF 422, HACCP y KOSHER KC listos para producir bajo tu marca.', 'body_en' => 'We are your plant. TIF 422, HACCP and KOSHER KC ready to produce under your brand.'], ['title_es' => '¿Tu maquilador no tiene certificaciones?', 'title_en' => 'Co-packer lacks certifications?', 'body_es' => 'Sin TIF no entras a las grandes cadenas. Cambia a un maquilador que abra esas puertas.', 'body_en' => 'Without TIF you cannot enter major chains. Switch to a co-packer that opens those doors.'], ['title_es' => '¿Miedo a que filtren tu fórmula?', 'title_en' => 'Afraid your formula will leak?', 'body_es' => 'Firmamos NDA antes de cualquier reunión técnica. Tu fórmula es tuya, siempre.', 'body_en' => 'We sign NDA before any technical meeting. Your formula is yours, always.']],
                'process_steps'=> [['n' => '01', 'title_es' => 'NDA y brief', 'title_en' => 'NDA and brief', 'body_es' => 'Firmamos NDA. Presentas tu concepto, especie, cortes y mercado objetivo.', 'body_en' => 'We sign NDA. You present your product concept, species, cuts and target market.'], ['n' => '02', 'title_es' => 'Desarrollo de fórmula', 'title_en' => 'Formula development', 'body_es' => 'Definimos ficha técnica de corte, rendimiento, empaque y especificaciones de etiqueta.', 'body_en' => 'We define cut spec, yield, packaging and label specifications together.'], ['n' => '03', 'title_es' => 'Muestra y validación', 'title_en' => 'Sample and validation', 'body_es' => 'Producimos lote piloto. Ajustamos hasta validación completa del producto terminado.', 'body_en' => 'We produce pilot lot. We adjust until full finished product validation.'], ['n' => '04', 'title_es' => 'Producción y despacho', 'title_en' => 'Production and dispatch', 'body_es' => 'Programa de producción semanal bajo tu marca. Reportes de lote y certificados por embarque.', 'body_en' => 'Weekly production schedule under your brand. Lot reports and certificates per shipment.']],
            ],
        ];

        foreach ($channels as $data) {
            Channel::updateOrCreate(['slug->es' => $data['slug']['es']], $data);
        }
    }
}
